---
title: "NYCD Map"
author: "Nikola Misetic"
format: html
editor: visual
---

## Packages

```{r}
library(tidyverse)
library(tigris)
library(sf)
library(tidycensus)
library (dplyr)
library (ggplot2)
library(htmltools)
library(janitor)
library(here)
library(mapview)
library(leafsync)
library(leaflet.extras2)
options(tigris_class = "sf")
```

```{r}
myapikey <- "7ec164ce2e6d7eff05a3da72fa85dec41773e398"
census_api_key(myapikey, overwrite = TRUE)
```

## Nassau Map

```{r}
nassau_voters <- get_acs(
  geography = 'tract',
  variables = c( 
    median_age = 'B01002A_001'
  ),
  state = 'NY',
  county = '059',
  output = "wide",
  geometry = TRUE
)
```

```{r}
nassau_voters <- nassau_voters %>%
  select(-ends_with("M"))

colnames(nassau_voters) <- sub("E$", "", colnames(nassau_voters))
```

```{r}
mapview(nassau_voters, zcol = "median_age")
```

## Queens Map

```{r}
queens_voters <- get_acs(
  geography = 'tract',
  variables = c( 
    median_age = 'B01002A_001'
  ),
  state = 'NY',
  county = '081',
  output = "wide",
  geometry = TRUE
)
```

```{r}
queens_voters <- queens_voters %>%
  select(-ends_with("M"))

colnames(queens_voters) <- sub("E$", "", colnames(queens_voters))
```

```{r}
mapview(queens_voters, zcol = "median_age")
```

## Suffolk Map

```{r}
suffolk_voters <- get_acs(
  geography = 'tract',
  variables = c( 
    median_age = 'B01002A_001'
  ),
  state = 'NY',
  county = '103',
  output = "wide",
  geometry = TRUE
)
```

```{r}
suffolk_voters <- suffolk_voters %>%
  select(-ends_with("M"))

colnames(suffolk_voters) <- sub("E$", "", colnames(suffolk_voters))
```

```{r}
mapview(suffolk_voters, zcol = "median_age")
```
